apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-znrd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-znrd@sha256:952733af456fb62c1c28ca1f2c0b601a050ba70112865f881ecabcc1857364e9
        name: my-nodejs
        resources: {}
status: {}
